Bring back support for GPR visitors
openjdk/jol pull request #15
Opened 2021-04-12 16:00 UTC by s1ck

Hey @shipilev First of all: Thanks for this useful library. I wanted to switch from jol 0.10 to 0.15 in one of my projects because of some issues on openJDK 15. I discovered that the ability to register visitors had been removed at some point. The interface `org.openjdk.jol.info.GraphVisitor` is actually still around. I find that feature quite useful as it allows users to compute some custom statistics of the object graph. I tried to use the `GraphLayout` to access the GPRs, but it's all package-private.

It would be nice if we could bring the feature back. Also, if you think the approach is not ideal, we can maybe figure out something else.

Thanks for your time.

2021-04-12 16:15 UTC, s1ck commented
/signed

2021-04-14 05:51 UTC, stokito approved these changes

2021-04-20 14:22 UTC, s1ck commented
@stokito Thanks for the review! What are the next steps to get this merged / released?

2021-04-20 14:25 UTC, stokito commented
You have to sign OCA as the bot said you. Then wait while Alexey reviews the PR

2021-04-20 14:27 UTC, s1ck commented
Thanks. I did already sign the OCA. Let's wait then :)

2021-05-02 10:47 UTC, s1ck commented
gentle ping @shipilev Would be great if we could get this merged and released :)

2021-05-05 17:29 UTC, shipilev commented
Sorry this got neglected. The underlying reason to remove GPRs was to simplify (and thus optimize) the walkers. I'll try to arrange time to see what can be done here without sacrificing that again.

2021-05-07 15:22 UTC, s1ck commented
I can share our usage pattern. We are interested in the `path` and the `size`. Maybe it helps when designing a different / faster visitor logic: https://github.com/neo4j/graph-data-science/blob/master/proc/catalog/src/main/java/org/neo4j/gds/catalog/GraphMemoryUsageProc.java#L98-L149

2021-05-10 12:09 UTC, shipilev requested changes
I did some benchmarking, and I think what you have is nearly the best we can do. I would like to avoid a few (sometimes virtual) calls on the walker hotpath. To that extent, please consider this change (note the `Map` -> `HashMap` rewrite too):

```
    private final GraphVisitor[] visitors;
    private final HashMap<Class<?>, Long> sizeCache;

    public GraphWalker(GraphVisitor... visitors) {
        this.visitors = visitors;
        sizeCache = new HashMap<>();
    }
```

...and then inline `visitObject` into two use sites.

I think you would be able to do `new GraphWalker(gpr -> { ... }).walk(...)` then.

2021-05-12 05:34 UTC, shipilev commented
@s1ck, if you want to release it this week, please finish this up :) Otherwise, the release would slip until next week.

2021-05-17 09:54 UTC, shipilev commented
Hey @s1ck, tell me what your plan is, so we can... err... plan accordingly. I think everything is ready for the release, if you want to hook this patch up there too.

2021-05-20 15:32 UTC, shipilev commented
Pinging @s1ck again!

2021-05-21 09:48 UTC, shipilev approved these changes
Thanks, this is good to go in.

2021-05-21 10:00 UTC, s1ck commented
/integrate

2021-05-21 10:02 UTC, s1ck commented
@shipilev thanks for the review and sorry for not reacting so quickly :see_no_evil:

2021-05-21 10:16 UTC, shipilev commented
No problem at all.

/sponsor

2021-05-21 10:17 UTC, closed without merging

2021-05-21 12:19 UTC, shipilev commented
Delivered in JOL 0.16.